name:shiva ci workflow

on:
  push:

jobs:
  build:  #name of the job
      runs-on: ubuntu-latest #GitHub runners
      steps:
        - name: checkout code
        - uses: actions/checkout@v4 #clone the code and checkout action to checkout the code

        - name: Setup Docker
        - uses: docker/setup-buildx-action@v4 #setup buildx action to build docker images





    